application: frcgamesense-fantasy-frc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: guestbook-steph.application

libraries:
- name: webapp2
  version: latest